version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/www/localhost/htdocs
    restart: unless-stopped

  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ./data:/var/www/localhost/htdocs/
    depends_on:
      - app
    ports:
      - "${LEGBA_PORT:-9880}:80"
    tty: true